-- Seed 20 demo products modelled on real Funky Friends Factory patterns
-- (funkyfriendsfactory.com/patterns). Prices in AUD, image_url/download_url
-- left NULL so the admin can upload real media via /admin/products → Media.
--
-- Idempotent: ON CONFLICT(slug) DO UPDATE. Re-running refreshes the sample
-- fields without creating duplicates.

INSERT INTO products (name, slug, price, description, short_description, category, difficulty, is_free, is_new, is_featured)
VALUES
  ('Honey Teddy', 'honey-teddy', 0.00,
    'My signature beginner teddy bear — Honey Teddy is the perfect first soft-toy project. Simple curves, minimal pieces, and a finished toy you''ll be proud to give as a gift. Full-size templates, step-by-step photo instructions, and a materials list included. Finished size approximately 30cm tall.',
    'The perfect starter teddy — simple curves, photo instructions, approx 30cm tall.',
    'beginner', 'beginner', 1, 0, 1),
  ('Ben the Beginner Bear', 'ben-beginner-bear', 12.99,
    'Ben is another lovely first-time project, designed to teach the fundamentals of stuffed-toy sewing — pin placement, curved seams, and ladder stitching. Photo tutorial + printable pattern pieces. Great for classroom use.',
    'Fundamentals-focused beginner bear with a clear photo tutorial.',
    'beginner', 'beginner', 0, 0, 1),
  ('Fifi Fox', 'fifi-fox', 12.99,
    'Fifi Fox is a cuddly woodland toy with a big bushy tail and pointy ears. Intermediate-level project with full-size templates, step-by-step photo instructions, and fabric suggestions. Stands about 35 cm tall.',
    'Cuddly woodland fox with a bushy tail, approx 35cm.',
    'toy-sewing-patterns', 'intermediate', 0, 0, 1),
  ('Ellie Elephant', 'ellie-elephant', 12.99,
    'Sweet and sturdy elephant pattern with big floppy ears and a curly trunk. Includes detailed photo instructions, full-size pattern pieces, and fabric-choice tips.',
    'Floppy-eared elephant with a curly trunk, approx 30cm.',
    'toy-sewing-patterns', 'intermediate', 0, 0, 0),
  ('Harmony Highland Cow', 'harmony-highland-cow', 12.99,
    'Harmony is the Highland Cow of your dreams — huge shaggy fringe, gentle eyes, sturdy horns. Uses fleece and felt. Intermediate to advanced techniques around the face + horns.',
    'Shaggy-fringed Highland Cow with character for days.',
    'toy-sewing-patterns', 'intermediate', 0, 1, 1),
  ('Aristotle Axolotl', 'aristotle-axolotl', 12.99,
    'Aristotle the Axolotl — the quirkiest critter in the collection! Feathery gills and a gentle smile. Great conversation piece. Intermediate skill level.',
    'Quirky axolotl with feathery gills.',
    'toy-sewing-patterns', 'intermediate', 0, 1, 0),
  ('Patty the Cow', 'patty-cow', 12.99,
    'A classic spotty cow pattern — perfect for farm-themed nurseries. Simple construction, loads of personality.',
    'Classic spotty farm cow, great for nursery gifts.',
    'toy-sewing-patterns', 'beginner', 0, 0, 0),
  ('Charlie Cockatoo', 'charlie-cockatoo', 12.99,
    'Our very own Aussie cockatoo! A sulphur-crested sweetheart with a movable crest. Intermediate project using felt feather detailing.',
    'Sulphur-crested Aussie cockatoo with felt feathers.',
    'toy-sewing-patterns', 'intermediate', 0, 0, 0),
  ('Baby Bunny Rabbit', 'baby-bunny-rabbit', 12.99,
    'A baby-safe bunny, constructed without small attached pieces — perfect for little ones. Oversized ears, soft fleece body.',
    'Baby-safe bunny with oversized ears, no small parts.',
    'toy-sewing-patterns', 'beginner', 0, 0, 1),
  ('Dizzy Dolphin', 'dizzy-dolphin', 12.99,
    'A playful dolphin pattern with a contrast belly and a cheeky smile. Intermediate curves in the tail flukes.',
    'Playful dolphin with a contrast belly.',
    'toy-sewing-patterns', 'intermediate', 0, 0, 0),
  ('Plattie Platypus', 'plattie-platypus', 12.99,
    'Platypus pattern capturing Australia''s most unique critter — flat tail, duck bill, webbed feet. Intermediate project.',
    'Uniquely Australian platypus with a flat tail + duck bill.',
    'toy-sewing-patterns', 'intermediate', 0, 1, 0),
  ('Reggie Reindeer', 'reggie-reindeer', 12.99,
    'A classic Christmas reindeer with a red nose and fabric antlers. Sized to sit under the tree.',
    'Classic Christmas reindeer, tree-side size.',
    'seasonal', 'intermediate', 0, 0, 0),
  ('Mrs. Claus Christmas Doll', 'mrs-claus-doll', 12.99,
    'A charming Mrs. Claus doll with removable apron + glasses. Perfect Christmas mantle decoration or nanna gift. Advanced detailing on the face.',
    'Charming Mrs. Claus doll with removable apron.',
    'seasonal', 'advanced', 0, 0, 0),
  ('Easter Bunny', 'easter-bunny', 12.99,
    'Seasonal Easter bunny in pastel cottons. Includes carrot pattern pieces for a matching accessory.',
    'Pastel Easter bunny + carrot accessory.',
    'seasonal', 'intermediate', 0, 0, 0),
  ('Whitney Witch', 'whitney-witch', 12.99,
    'Halloween Whitney Witch with a pointy hat, striped stockings, and a mini broom. One of our most popular Halloween patterns.',
    'Halloween witch with striped stockings + mini broom.',
    'seasonal', 'advanced', 0, 0, 0),
  ('Silly Scrap Snakes', 'silly-scrap-snakes', 0.00,
    'Use up your fabric scraps with this super-simple snake pattern. Perfect beginner project, great for rainy-day kids'' sewing sessions.',
    'Super-simple snake — the perfect scrap-buster.',
    'fun-stuff-from-scraps', 'beginner', 1, 0, 0),
  ('Easy Whale', 'easy-whale', 0.00,
    'A beginner-friendly whale with just 6 pattern pieces. Ideal for first-timers or a classroom workshop.',
    'Beginner whale with just 6 pieces — classroom friendly.',
    'fun-stuff-from-scraps', 'beginner', 1, 1, 1),
  ('Kelsey the Keepsake Unicorn', 'kelsey-keepsake-unicorn', 12.99,
    'Turn a beloved baby blanket or outgrown sleepsuit into a memory unicorn. Detailed keepsake instructions included.',
    'Memory unicorn made from keepsake fabrics.',
    'doll-sewing-patterns', 'advanced', 0, 0, 1),
  ('Blue the Keepsake Dog', 'blue-keepsake-dog', 12.99,
    'Companion to Kelsey — the Blue keepsake dog. Turn treasured old clothes into a forever friend.',
    'Keepsake dog made from treasured clothes.',
    'doll-sewing-patterns', 'advanced', 0, 0, 0),
  ('Bedtime Baby Doll', 'bedtime-baby-doll', 12.99,
    'A snuggly baby doll in a sleeping gown. Soft, safe, and perfect for gifting to toddlers.',
    'Snuggly bedtime baby doll in a sleeping gown.',
    'doll-sewing-patterns', 'intermediate', 0, 0, 0)

ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  price = excluded.price,
  description = excluded.description,
  short_description = excluded.short_description,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_free = excluded.is_free,
  is_new = excluded.is_new,
  is_featured = excluded.is_featured,
  updated_at = datetime('now');
